# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b50eeae8a87f161aa7a8b2b8dd6738389e8ca216a14aafd8eed87a7bb5003a41df2788c063968a178045672045681438447e6bf77eaf342d09765a8d5c91d3f8

test:
  secret_key_base: 517d3d7fb8e958a4728ac42a3a25e246779916b12986c5f8ec1fa2160cea24fe238e6559366dfa056280b9c84e7584446267b5e8a4371147f64533f6867878c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
