# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 765d8657c54d4626ca4f9bedcdfdd99dc277df43947da9d4fa1ddb89cbefbe8773d41f666d20f1f2d90703607950572c768bda948c170e7da009b39bf6a64e96

test:
  secret_key_base: adda004f3fca7528b0a3e66ae5dc3216cc7755f7ae0a11d300271bb9dbf3510f39e7aa6cd43032776a1b33f5fd4af763053033b9b5f6c0cc391984cf0c03a815

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
